document.getElementById("incIterations").addEventListener('click', function () { Module.ccall('incIterations', null, null, null); });
document.getElementById("decIterations").addEventListener('click', function () { Module.ccall('decIterations', null, null, null); });
document.getElementById("changeColor").addEventListener('click', function () { Module.ccall('changeColor', null, null, null); });
document.getElementById("zoomMinus").addEventListener('click', function () { Module.ccall('zoomMinus', null, null, null); });
document.getElementById("zoomPlus").addEventListener('click', function () { Module.ccall('zoomPlus', null, null, null); });
document.getElementById("w").addEventListener('click', function () { Module.ccall('w', null, null, null); });
document.getElementById("a").addEventListener('click', function () { Module.ccall('a', null, null, null); });
document.getElementById("s").addEventListener('click', function () { Module.ccall('s', null, null, null); });
document.getElementById("d").addEventListener('click', function () { Module.ccall('d', null, null, null); });